import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Poppins } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "TeleBank",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${roboto.variable} ${poppins.variable} overflow-hidden`}
      lang="pt"
    >
      <body className="h-full w-full font-roboto overflow-hidden">
        {children}
      </body>
    </html>
  );
}
